apiVersion: apps/v1 #Each object can be versioned. That means the data structure of the object can change between different versions.
kind: Deployment #The kind of object that should be created.
metadata:
  name: nginx-deployment
spec: 
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80